apiVersion: v1
kind: Service
metadata:
  name: trading-bot-service
spec:
  selector:
    app: trading-bot
  ports:
  - name: http
    port: 80
    targetPort: 80

  - name: metrics
    port: 8000
    targetPort: 8000